### ISSUE TITLE
Flask-MQTT Won't Install on Raspberry Pi 

### ISSUE THREAD

**Issue by crood58** [MrLeeh/Flask-MQTT#11]
I have tried to install Flask-MQTT on my Raspberry Pi Zero with the latest version of raspbian. I keep getting the error shown in the attached screenshot. Does Flask-MQTT not work on a pi? 

![capture](https://user-images.githubusercontent.com/3356264/27409907-f78a4204-56b1-11e7-86b4-28078f9a67bd.PNG)

Thanks in advance for the help. 

Chris

**Comment by MrLeeh** [comment]
Flask-MQTT is written for Python3. If you use `pip install` it probably uses Python2. Try `pip3 install` or `pip3.5 install` to install it for python3. Or you may use a virtual environment.

**Comment by crood58** [comment]
I got to work. I recommend updating the readme on guthub, so this in the documentation for installation,

**Comment by MrLeeh** [comment]
Thanks for the hint. In fact I decided to make it downward compatible to Python2.7 in the meantime as it hasn't been that much hassle. So now you can use it on Python 2.7 and Python 3.+
