### ISSUE TITLE
Not receiving any data from broker

### ISSUE THREAD

**Issue by davidtweaver** [MrLeeh/Flask-MQTT#16]
Hello,

I'm not sure if this is an issue, or if I'm just misunderstanding the documentation:

- I have a Mosquitto broker running on a Raspberry Pi, and when I run the Flask publish / subscribe script on my laptop, I can see that it has definitely connected, but in the log on the Flask side of things I never see any data in the @mqtt.on_log() function

I have a topic called hello/world which I can subscribe to via the command line but can't seem to access through flask.
My subscribe function looks like this (the print statement here never produces anything either)

    def handle_subscribe(json_str):
        data = json.loads(json_str)
        print("test test test")
        mqtt.subscribe('hello/world')

I'm not sure if I'm just misunderstanding how to use the example code, so apologies if so

**Comment by MrLeeh** [comment]
@davidtweaver This could be a problem with your Flask configuration. Could you post your Flask code, please.

**Comment by davidtweaver** [comment]
My code looks like this (I've left the publish bit as it was because I don't need it just yet)

`

import eventlet
import json
from flask import Flask, render_template
from flask_mqtt import Mqtt
from flask_socketio import SocketIO
from flask_bootstrap import Bootstrap

eventlet.monkey_patch()

app = Flask(__name__)
app.config['SECRET'] = 'my secret key'
app.config['TEMPLATES_AUTO_RELOAD'] = True
app.config['MQTT_BROKER_URL'] = '192.168.43.101'
app.config['MQTT_BROKER_PORT'] = 1883
app.config['MQTT_USERNAME'] = ''
app.config['MQTT_PASSWORD'] = ''
app.config['MQTT_KEEPALIVE'] = 5
app.config['MQTT_TLS_ENABLED'] = False

# Parameters for SSL enabled
# app.config['MQTT_BROKER_PORT'] = 8883
# app.config['MQTT_TLS_ENABLED'] = True
# app.config['MQTT_TLS_INSECURE'] = True
# app.config['MQTT_TLS_CA_CERTS'] = 'ca.crt'

mqtt = Mqtt(app)
socketio = SocketIO(app)
bootstrap = Bootstrap(app)

print(app)

@app.route('/')
def index():
    print('render index route')
    return render_template('index.html')


@socketio.on('publish')
def handle_publish(json_str):
    data = json.loads(json_str)
    mqtt.publish(data['topic'], data['message'])


@socketio.on('subscribe')
def handle_subscribe(json_str):
    data = json.loads(json_str)
    print("test test test")
    mqtt.subscribe('hello/world')


@mqtt.on_message()
def handle_mqtt_message(client, userdata, message):
    print('handle message')
    data = dict(
        topic=message.topic,
        payload=message.payload.decode()
    )
    print(data)
    socketio.emit('mqtt_message', data=data)


@mqtt.on_log()
def handle_logging(client, userdata, level, buf):
    print(level, buf)


if __name__ == '__main__':
    print(app)
    socketio.run(app, host='0.0.0.0', port=5000, use_reloader=True, debug=True)

`

**Comment by MrLeeh** [comment]
Actually I can not find an error in your code. Could be an issue with your Mosquitto server. Have you tried this example with another Mosquitto server like hivemq (see the provided example)?

**Comment by davidtweaver** [comment]
Ah looks like it was an issue with my websockets rather than the MQTT side of things. I've got it all working now. Thanks for your help!

**Comment by MrLeeh** [comment]
@davidtweaver Glad it worked out for you.
