### ISSUE TITLE
Can't install on ubuntu

### ISSUE THREAD

**Issue by VitorHugoAguiar** [MrLeeh/Flask-MQTT#3]
Its possible to install on ubuntu? I am getting:
`vitor@miti:~/Desktop$ pip install flask-mqtt

Collecting flask-mqtt
  Could not find a version that satisfies the requirement flask-mqtt (from versions: 0.0.1.macosx-10.12-x86_64)

No matching distribution found for flask-mqtt
`

**Comment by MrLeeh** [comment]
Are you on Python2? Flask-MQTT is only compatible with Python3
