### ISSUE TITLE
It seems that the module will create two instances of mqtt client.

### ISSUE THREAD

**Issue by qianchenzhumeng** [MrLeeh/Flask-MQTT#8]
When the example code is running, the broker was connected by tow clients simultaneously
. In this case, if there is a message coming from broker, the handle_mqtt_message function will be called twice.

**Comment by qianchenzhumeng** [comment]
The problem isn't caused by this module. Setting "use_reloader" to "False" can resolve it.

**Comment by MrLeeh** [comment]
Thank you for the feedback. I know this issue with the developer server starting up twice. Actually the ideal beahivour for the mqtt client would be to start only once even if there are two flask applications. If you have any hints how to achieve this, you' re very welcome. I' ll give it a closer look asap. Greetings

**Comment by qianchenzhumeng** [comment]
Thanks. I have doubts about whether making mqtt as a plugin of flask is feasible. There often are many many worker processes when the flask program is launched by WSGI HTTP Server, such as gunicorn. According to current design idea, it's terrible when using the WSGI HTTP Server to launch flask program.

**Comment by MrLeeh** [comment]
I see two ways to tackle this:

1. there will only be one Mqtt client thread no matter how many Flask clients there are. This has the touch of simplicity but doesn't scale well as all messages will be computed by one single Mqtt client even if there are multiple Flask workers. But it would ensure there are no multiple message deliveries.

2. create as many Mqtt worker threads as Flask workers and let each Mqtt client process Publishing messages but only one will handle subscriptions. I guess this would scale better but will probably be more complicated in the making.

Also I'm not sure if it even makes sense to use multiple Mqtt workers as there is only one Server they can communicate with.

**Comment by MrLeeh** [comment]
Actually I just tried Flask-MQTT with multiple instances of the Flask application using gunicorn or the debugger. It is right that there are two MQTT clients created here. And this is the way it should be as each of them is assigned to a separate WSGI application object. However you need to make sure you won' t subscribe to the same topic with both clients. This doesn' t happen in the example as the subscriptions are made dynamically via socketio. However it could be difficult dealing with this if you hard-code the subscriptions in your application.
